kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-operator-cluster
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims",persistentvolumeclaims/finalizers,"persistentvolumeclaims/status"]
    verbs: ["*","get", "list", "watch", "update"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get","list","create","watch","patch","update"]

  - apiGroups: ["extensions"]
    resources: ["ingresses","ingresses/status"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: [""]
    resources: [ingresses","ingresses/status"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: [""]
    resources: ["podsecuritypolicies"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","create","delete","patch"]

  - apiGroups: [""]
    resources: ["pods/exec","pods/log","pods/portforward"]
    verbs: ["get","list","create","delete","watch"]

  - apiGroups: ["icp.ibm.com"]
    resources: ["images"]
    verbs: ["get","list","create","watch"]
  
  - apiGroups: [""]
    resources: ["deployments/finalizers"]
    verbs: ["watch", "get","list","create", "update","delete","patch"]
  
  - apiGroups: ["apps"]
    resources: ["deployments/finalizers"]
    verbs: ["watch", "get","list","create", "update","delete","patch"]
  
  - apiGroups: ["extensions"]
    resources: ["deployments","deployments/finalizers"]
    verbs: ["watch", "get","list","create", "update","delete","patch"]
  
  - apiGroups: ["extensions"]
    resources: ["replicasets","replicasets/finalizers"]
    verbs: ["get","list","update","delete"]
  
  - apiGroups: ["apps"]
    resources: ["replicasets/finalizers"]
    verbs: ["get","list","update","delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["create","patch","watch","delete"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get","create","list","update","delete","patch","watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["create","get","patch","list", "watch"]

