apiVersion: apps/v1
kind: Deployment
metadata:
  name: codewind-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: codewind-operator
  template:
    metadata:
      labels:
        name: codewind-operator
    spec:
      serviceAccountName: codewind-operator
      containers:
        - name: codewind-operator
          image: REPLACE_IMAGE
          command:
          - codewind-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "codewind-operator"
